create table test_table_all_columns__numeric (
column_smallint smallint,
column_integer integer,
column_bigint bigint,
column_decimal decimal,
column_numeric numeric,
column_numeric_limit numeric(6,4),
column_real real,
column_double_precision double precision,
column_smallserial smallserial,
column_serial serial,
column_bigserial bigserial,
column_alias_int8 int8,
column_alias_serial8 serial8,
column_alias_float8 float8,
column_alias_int int,
column_alias_int4 int4,
column_alias_decimal decimal,
column_alias_decimal_limit decimal(6,4),
column_alias_float4 float4,
column_alias_int2 int2,
column_alias_serial2 serial2,
column_alias_serial4 serial4
);